### PR TITLE
Lots of changes from the last 1.5 years

### PR DESCRIPTION
**Pull request by omermazig**
Hey,

I did A LOT of work on your packege, but as before - on my own branch instead of on a fork. This time I invested the time to jedi mind-trick git to think my work was indeed on a fork, so now it shows all of my commit history in the branch (which is excellent). The downside was I had to "reset -HARD" the fork to 3f13688b608b5ad2b3fc0fa7fc09e515a9cf38ea, Which means it's missing all of the changes you've made from that point on (I couldn't really find a "nice" way of restoring them back. You're wellcome to if you like)

I have another project that works with this package as a dependency, And from what I can tell it works fine now. 

I'll continue working from this fork whether you'll merge it or not, but I think you should. I've dedicated a lot of time on this and it's better now IMO.

### CODE REVIEW

**Comment by danielmcintosh1** [comment]
Super cool! Bradley is offline tonight but I know he'll take a look when he gets back online.
Thanks for all your work here. Feel free to email me at daniel@cardinaladvising.com or bradley@cardinaladvising.com if you have any non public comments. We are still very active.

**Comment by bradleyfay** [comment]
There are a lot of merge conflicts. This might take a few days to sort out @omermazig

**Comment by omermazig** [comment]
Thanks! 


I have not formally tested it, but I'm using it a lot in a variety of ways (https://bitbucket.org/omermazig/nba_stats_provider) so I'm pretty sure most of it works. Unfortunately, that all the guarantees I have.

**Comment by bradleyfay** [comment]
Merged in all changes to dev branch

**Pull request merged**
